# This file contains values from Cookiecutter

default_context:
  project_name: "snapp-mle-task"
  project_description: "Snapp Pin Fixing Problem Task"
  organization: "snapp"
  license: "MIT"
  minimal_python_version: 3.12
  github_name: "rezashabrang"
  email: "rezashabrang.m@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
